[project]
name = "ai-middleware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "mistralai>=1.9.11",
    "pydantic-settings>=2.11.0",
    "ruff>=0.14.4",
]
