[project]
name = "ai-middleware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.4",
    "ruff>=0.14.3",
]

[tool.uv.workspace]
members = [
    "ai_middleware",
]
